#Global configuration
spring.application.name=TaskMaster Backend

#Tomcat configuration
server.port=9000

#Log level configuration
logging.level.root=error
logging.level.com.taskmaster=info
logging.level.org.springframework.boot.autoconfigure.h2=INFO
logging.level.org.springframework.web.embedded.tomcat=INFO

#H2 Configuration
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.h2.console.enabled=true